@host = localhost:8080

//Create Product
POST http://{{host}}/api/products HTTP/1.1
content-type: application/json

{
    "name": "test-product-2",
    "description": "random-description",
    "price": 100.00
}

###

// Get All Products
GET http://{{host}}/api/products HTTP/1.1
content-type: application/json

// Update Product
PUT http://{{host}}/api/products/2 HTTP/1.1
content-type: application/json

{
    "name": "test-product-2",
    "description": "updated-random-description",
    "price": 100.00
}

// Delete Product
DELETE http://{{host}}/api/products/2 HTTP/1.1

// Demo Association
GET http://{{host}}/demo/associations/menuproducts HTTP/1.1
content-type: application/json